// templates/vue/sidebar/SidebarApp.vue
<template>
  <div class="sidebar_app">
    <img class="sidebar_logo" :src="vueLogo" alt="The Vue logo" />
    <h1 class="sidebar_title">Welcome to your<br />Vue Extension</h1>
    <p class="sidebar_description">
      Learn more about creating cross-browser extensions at
      <a href="https://extension.js.org" target="_blank" rel="noopener noreferrer">
        https://extension.js.org
      </a>
    </p>
  </div>
</template>

<script setup lang="ts">
import vueLogo from '../images/vue.png'
</script>

// templates/svelte/sidebar/SidebarApp.svelte
<script lang="ts">
  import logo from '../images/svelte.png'
</script>

<div class="sidebar_app">
  <img class="sidebar_logo" src={logo} alt="The Svelte logo" />
  <h1 class="sidebar_title">
    Welcome to your
    <br />
    Svelte Extension
  </h1>
  <p class="sidebar_description">
    Learn more about creating cross-browser extensions at{' '}
    <a
      href="https://extension.js.org"
      target="_blank"
      rel="noopener noreferrer"
    >
      https://extension.js.org
    </a>
  </p>
</div>
