// examples/_not_working_monorepo/apps/extension/options/OptionsApp.tsx
import './styles.css'
import reactLogo from '../images/react.png'

export default function NewTabApp() {
  return (
    <header>
      <h1>
        <img
          className="react"
          src={reactLogo}
          alt="The React logo"
          width="120px"
        />
        <br />
        Welcome to your React Extension.
      </h1>
      <p>
        Learn more about creating cross-browser extensions at{' '}
        <a href="https://extension.js.org" target="_blank">
          https://extension.js.org
        </a>
        .
      </p>
    </header>
  )
}

// examples-v2/svelte/options/OptionsApp.svelte
<script lang="ts">
  let message = 'Welcome to your Svelte Extension.'
</script>

<header>
  <h1>
    <img class="svelte" src="/logo.png" alt="The Svelte logo" width="120px" />
    <br />
    {message}
  </h1>
  <p>
    Learn more about creating browser extensions at
    <a href="https://extension.js.org" target="_blank">
      https://extension.js.org
    </a>.
  </p>
</header>
