// examples-v2/svelte/options/OptionsApp.svelte
<script lang="ts">
  let message = 'Welcome to your Svelte Extension.'
</script>

<header>
  <h1>
    <img class="svelte" src="/logo.png" alt="The Svelte logo" width="120px" />
    <br />
    {message}
  </h1>
  <p>
    Learn more about creating browser extensions at
    <a href="https://extension.js.org" target="_blank">
      https://extension.js.org
    </a>.
  </p>
</header>

// examples-v2/vue/options/OptionsApp.vue
<script lang="ts">
export default {
  data() {
    return {
      message: 'Welcome to your Vue Extension.'
    }
  }
}
</script>
<template>
  <header>
    <h1>
      <img
        class="vue"
        src="/logo.svg"
        alt="The Vue logo"
        width="120px"
      />
      <br />
      {{message}}
    </h1>
    <p>
      Learn more about creating cross-browser extensions at 
      <a href="https://extension.js.org" target="_blank">
        https://extension.js.org
      </a>
      .
    </p>
  </header>
</template>
