// examples/new-svelte/newtab/NewTabApp.svelte
<script lang="ts">
  let message = 'Welcome to your Svelte Extension.'
</script>

<header>
  <h1>
    <img class="svelte" src="/logo.png" alt="The Svelte logo" width="120px" />
    <br />
    {message}
  </h1>
  <p>
    Learn more about creating browser extensions at
    <a href="https://extension.js.org" target="_blank">
      https://extension.js.org
    </a>
    .
  </p>
</header>

// programs/create/templates/react/template/newtab/NewTabApp.jsx
import React from 'react'
import 'sakura.css'
import './base.css'
import reactLogo from '../public/react.png'

export default function NewTabApp() {
  return (
    <header>
      <h1>
        <img class="react" src={reactLogo} alt="The React logo" width="120px" />
        <br />
        Welcome to your React Extension.
      </h1>
      <p>
        Learn more about creating browser extensions at{' '}
        <a href="https://extension.js.org" target="_blank">
          https://extension.js.org
        </a>
        .
      </p>
    </header>
  )
}
